apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/code-crusher/test-nginx'
    targetRevision: HEAD
    path: './chart'
    helm:
      valueFiles:
        - values/values-main-us-west-1.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginxer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: appType
      value: general